name: pull-request-preview-teardown
on:
  pull_request:
    types: [closed]
jobs:
  harbor-teardown:
    if: |
      github.event.pull_request.draft == false &&
      (
          (
              contains(github.event.pull_request.title, '[preview]') &&
              github.event.action == 'closed'
          ) ||
          (
              github.event.action == 'edited' &&
              contains(github.event.changes.title.from, '[preview]') &&
              !contains(github.event.pull_request.title, '[preview]')
          )
      )
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    steps:
      - name: Start Shipping
        env:
          FORGE_TOKEN: ${{ secrets.FORGE_TOKEN }}
          FORGE_DOMAIN: prvoisioner.test
          FORGE_SERVER: ${{ secrets.FORGE_SERVER }}
          FORGE_NGINX_TEMPLATE: ${{ secrets.FORGE_NGINX_TEMPLATE }}
          FORGE_GIT_REPOSITORY: ${{ github.repository }}
          FORGE_GIT_BRANCH: ${{ github.head_ref }}
          FORGE_SUBDOMAIN_PATTERN: /^[a-z]{1,5}-(\d{1,5})/i
        run: |
          curl -LJO https://github.com/mehrancodes/forge-harbor/releases/download/v0.0.2/harbor
          chmod +x ./harbor
          ./harbor teardown
