name: pull-request-preview-teardown
on:
  pull_request:
    types: [closed, edited]
env:
  HARBOR_REF: mehrancodes/feat-gitlab-connection-review
jobs:
  harbor-teardown:
    if: |
      github.event.pull_request.draft == false &&
      (
          (
              contains(github.event.pull_request.title, '[harbor]') &&
              github.event.action == 'closed'
          ) ||
          (
              github.event.action == 'edited' &&
              contains(github.event.changes.title.from, '[harbor]') &&
              !contains(github.event.pull_request.title, '[harbor]')
          )
      )
    concurrency:
      group: harbor-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Install Harbor
        run: git clone --depth 1 -b "$HARBOR_REF" https://github.com/mehrancodes/laravel-harbor.git
      - name: Start Teardown
        env:
          FORGE_TOKEN: ${{ secrets.HARBOR_V2_FORGE_TOKEN }}
          FORGE_ORGANIZATION: ${{ vars.HARBOR_V2_FORGE_ORGANIZATION }}
          FORGE_SERVER: ${{ secrets.HARBOR_V2_FORGE_SERVER }}
          FORGE_DOMAIN: ${{ vars.HARBOR_V2_FORGE_DOMAIN }}
          FORGE_GIT_REPOSITORY: ${{ github.repository }}
          FORGE_GIT_BRANCH: ${{ github.head_ref }}
          SUBDOMAIN_NAME: pr-${{ github.event.number }}

          FORGE_DEPLOY_KEY: true
          FORGE_GIT_REPOSITORY_URL: "git@github.com:${{ github.repository }}.git"
          FORGE_GIT_PROVIDER: custom
          GIT_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          cd laravel-harbor
          composer install --no-interaction --prefer-dist
          php harbor teardown
