name: pull-request-preview-teardown
on:
  pull_request:
    types: [closed, edited]
jobs:
  harbor-teardown:
    if: |
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2
    steps:
      - name: Install Harbor
        run: git clone https://github.com/RobertBoes/laravel-harbor.git -b patch-1
      - name: Start Teardown
        env:
          FORGE_TOKEN: ${{ secrets.FORGE_TOKEN }}
          FORGE_SERVER: ${{ secrets.FORGE_SERVER }}
          FORGE_GIT_REPOSITORY: ${{ github.repository }}
          FORGE_GIT_BRANCH: ${{ github.head_ref }}
          FORGE_DOMAIN: laravel-harbor.com
        run: |
          cd laravel-harbor
          composer install
          php harbor teardown
