name: pull-request-preview-teardown
on:
  pull_request:
    types: [closed, edited]
jobs:
  harbor-teardown:
    if: |
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2
    steps:
      - name: Install Harbor
        run: git clone https://github.com/RobertBoes/laravel-harbor.git -b patch-1
      - name: Start Teardown
        env:
          FORGE_TOKEN: ${{ secrets.FORGE_TOKEN }} # Your Forge token
          FORGE_SERVER: ${{ secrets.FORGE_SERVER }} # The Forge server id you want to make a new site on
          FORGE_GIT_REPOSITORY: ${{ github.repository }} # mehrancodes/harbor-laravel-sample
          FORGE_GIT_BRANCH: ${{ github.head_ref }} # plt-123-add-new-feature
          FORGE_DOMAIN: laravel-harbor.com
          FORGE_ENV_KEYS: ${{ vars.LARAVEL_ENV_KEYS }}
          SUBDOMAIN_NAME: pr-${{ github.event.number }}
          FORGE_PHP_VERSION: php83
          FORGE_DEPLOY_SCRIPT: ${{ vars.FORGE_DEPLOY_SCRIPT }}

          # Indicates we want to deploy using deploy keys
          FORGE_GITHUB_DEPLOY_KEY: true
          # The git URL to be used in Forge
          FORGE_GIT_REPOSITORY_URL: "git@github.com:${{ github.repository }}.git"
          # We have to set the provider to 'custom', since Forge otherwise wouldn't use the deploy-key
          FORGE_GIT_PROVIDER: custom
          # We set the token we got from our app, instead of the default token
          # As the default actions token does not have permissions to create a deploy key
          GIT_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          cd laravel-harbor
          composer install
          php harbor teardown
